// Generated by quicktype from the Anthropic OpenAPI spec.
// Do not edit manually — re-run `just generate` instead.

#![allow(dead_code)]
#![allow(clippy::redundant_field_names)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct CreateMessageParams {
    /// Top-level cache control automatically applies a cache_control marker to the last
    /// cacheable block in the request.
    pub cache_control: Option<CacheControlEphemeral>,

    /// Container identifier for reuse across requests.
    pub container: Option<Container>,

    /// Specifies the geographic region for inference processing. If not specified, the
    /// workspace's `default_inference_geo` is used.
    pub inference_geo: Option<String>,

    /// The maximum number of tokens to generate before stopping.
    ///
    /// Note that our models may stop _before_ reaching this maximum. This parameter only
    /// specifies the absolute maximum number of tokens to generate.
    ///
    /// Set to `0` to populate the [prompt
    /// cache](https://platform.claude.com/docs/en/build-with-claude/prompt-caching#pre-warming-the-cache)
    /// without generating a response.
    ///
    /// Different models have different maximum values for this parameter.  See
    /// [models](https://platform.claude.com/docs/en/about-claude/models/overview) for details.
    pub max_tokens: i64,

    /// Input messages.
    ///
    /// Our models are trained to operate on alternating `user` and `assistant` conversational
    /// turns. When creating a new `Message`, you specify the prior conversational turns with the
    /// `messages` parameter, and the model then generates the next `Message` in the
    /// conversation. Consecutive `user` or `assistant` turns in your request will be combined
    /// into a single turn.
    ///
    /// Each input message must be an object with a `role` and `content`. You can specify a
    /// single `user`-role message, or you can include multiple `user` and `assistant` messages.
    ///
    /// If the final message uses the `assistant` role, the response content will continue
    /// immediately from the content in that message. This can be used to constrain part of the
    /// model's response.
    ///
    /// Example with a single `user` message:
    ///
    /// ```json
    /// [{"role": "user", "content": "Hello, Claude"}]
    /// ```
    ///
    /// Example with multiple conversational turns:
    ///
    /// ```json
    /// [
    /// {"role": "user", "content": "Hello there."},
    /// {"role": "assistant", "content": "Hi, I'm Claude. How can I help you?"},
    /// {"role": "user", "content": "Can you explain LLMs in plain English?"},
    /// ]
    /// ```
    ///
    /// Example with a partially-filled response from Claude:
    ///
    /// ```json
    /// [
    /// {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C)
    /// Sun"},
    /// {"role": "assistant", "content": "The best answer is ("},
    /// ]
    /// ```
    ///
    /// Each input message `content` may be either a single `string` or an array of content
    /// blocks, where each block has a specific `type`. Using a `string` for `content` is
    /// shorthand for an array of one content block of type `"text"`. The following input
    /// messages are equivalent:
    ///
    /// ```json
    /// {"role": "user", "content": "Hello, Claude"}
    /// ```
    ///
    /// ```json
    /// {"role": "user", "content": [{"type": "text", "text": "Hello, Claude"}]}
    /// ```
    ///
    /// See [input
    /// examples](https://platform.claude.com/docs/en/build-with-claude/working-with-messages).
    ///
    /// Note that if you want to include a [system
    /// prompt](https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices#give-claude-a-role),
    /// you can use the top-level `system` parameter — there is no `"system"` role for input
    /// messages in the Messages API.
    ///
    /// There is a limit of 100,000 messages in a single request.
    pub messages: Vec<InputMessage>,

    /// An object describing metadata about the request.
    pub metadata: Option<Metadata>,

    pub model: String,

    /// Configuration options for the model's output, such as the output format.
    pub output_config: Option<OutputConfig>,

    /// Determines whether to use priority capacity (if available) or standard capacity for this
    /// request.
    ///
    /// Anthropic offers different levels of service for your API requests. See
    /// [service-tiers](https://platform.claude.com/docs/en/api/service-tiers) for details.
    pub service_tier: Option<ServiceTier>,

    /// Custom text sequences that will cause the model to stop generating.
    ///
    /// Our models will normally stop when they have naturally completed their turn, which will
    /// result in a response `stop_reason` of `"end_turn"`.
    ///
    /// If you want the model to stop generating when it encounters custom strings of text, you
    /// can use the `stop_sequences` parameter. If the model encounters one of the custom
    /// sequences, the response `stop_reason` value will be `"stop_sequence"` and the response
    /// `stop_sequence` value will contain the matched stop sequence.
    pub stop_sequences: Option<Vec<String>>,

    /// Whether to incrementally stream the response using server-sent events.
    ///
    /// See [streaming](https://platform.claude.com/docs/en/build-with-claude/streaming) for
    /// details.
    pub stream: Option<bool>,

    /// System prompt.
    ///
    /// A system prompt is a way of providing context and instructions to Claude, such as
    /// specifying a particular goal or role. See our [guide to system
    /// prompts](https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices#give-claude-a-role).
    pub system: Option<System>,

    /// Amount of randomness injected into the response.
    ///
    /// Defaults to `1.0`. Ranges from `0.0` to `1.0`. Use `temperature` closer to `0.0` for
    /// analytical / multiple choice, and closer to `1.0` for creative and generative tasks.
    ///
    /// Note that even with `temperature` of `0.0`, the results will not be fully deterministic.
    pub temperature: Option<f64>,

    pub thinking: Option<Thinking>,

    pub tool_choice: Option<ToolChoice>,

    /// Definitions of tools that the model may use.
    ///
    /// If you include `tools` in your API request, the model may return `tool_use` content
    /// blocks that represent the model's use of those tools. You can then run those tools using
    /// the tool input generated by the model and then optionally return results back to the
    /// model using `tool_result` content blocks.
    ///
    /// There are two types of tools: **client tools** and **server tools**. The behavior
    /// described below applies to client tools. For [server
    /// tools](https://platform.claude.com/docs/en/agents-and-tools/tool-use/server-tools), see
    /// their individual documentation as each has its own behavior (e.g., the [web search
    /// tool](https://platform.claude.com/docs/en/agents-and-tools/tool-use/web-search-tool)).
    ///
    /// Each tool definition includes:
    ///
    /// * `name`: Name of the tool.
    /// * `description`: Optional, but strongly-recommended description of the tool.
    /// * `input_schema`: [JSON schema](https://json-schema.org/draft/2020-12) for the tool
    /// `input` shape that the model will produce in `tool_use` output content blocks.
    ///
    /// For example, if you defined `tools` as:
    ///
    /// ```json
    /// [
    /// {
    /// "name": "get_stock_price",
    /// "description": "Get the current stock price for a given ticker symbol.",
    /// "input_schema": {
    /// "type": "object",
    /// "properties": {
    /// "ticker": {
    /// "type": "string",
    /// "description": "The stock ticker symbol, e.g. AAPL for Apple Inc."
    /// }
    /// },
    /// "required": ["ticker"]
    /// }
    /// }
    /// ]
    /// ```
    ///
    /// And then asked the model "What's the S&P 500 at today?", the model might produce
    /// `tool_use` content blocks in the response like this:
    ///
    /// ```json
    /// [
    /// {
    /// "type": "tool_use",
    /// "id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
    /// "name": "get_stock_price",
    /// "input": { "ticker": "^GSPC" }
    /// }
    /// ]
    /// ```
    ///
    /// You might then run your `get_stock_price` tool with `{"ticker": "^GSPC"}` as an input,
    /// and return the following back to the model in a subsequent `user` message:
    ///
    /// ```json
    /// [
    /// {
    /// "type": "tool_result",
    /// "tool_use_id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
    /// "content": "259.75 USD"
    /// }
    /// ]
    /// ```
    ///
    /// Tools can be used for workflows that include running client-side tools and functions, or
    /// more generally whenever you want the model to produce a particular JSON structure of
    /// output.
    ///
    /// See our [guide](https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview)
    /// for more details.
    pub tools: Option<Vec<Tool>>,

    /// Only sample from the top K options for each subsequent token.
    ///
    /// Used to remove "long tail" low probability responses. [Learn more technical details
    /// here](https://towardsdatascience.com/how-to-sample-from-language-models-682bceb97277).
    ///
    /// Recommended for advanced use cases only.
    pub top_k: Option<i64>,

    /// Use nucleus sampling.
    ///
    /// In nucleus sampling, we compute the cumulative distribution over all the options for each
    /// subsequent token in decreasing probability order and cut it off once it reaches a
    /// particular probability specified by `top_p`.
    ///
    /// Recommended for advanced use cases only.
    pub top_p: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct CacheControlEphemeral {
    /// The time-to-live for the cache control breakpoint.
    ///
    /// This may be one the following values:
    /// - `5m`: 5 minutes
    /// - `1h`: 1 hour
    ///
    /// Defaults to `5m`. See [prompt caching
    /// pricing](https://platform.claude.com/docs/en/build-with-claude/prompt-caching) for
    /// details.
    pub ttl: Option<Ttl>,

    #[serde(rename = "type")]
    pub cache_control_ephemeral_type: CacheControlEphemeralType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum CacheControlEphemeralType {
    Ephemeral,
}

/// The time-to-live for the cache control breakpoint.
///
/// This may be one the following values:
/// - `5m`: 5 minutes
/// - `1h`: 1 hour
///
/// Defaults to `5m`. See [prompt caching
/// pricing](https://platform.claude.com/docs/en/build-with-claude/prompt-caching) for
/// details.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub enum Ttl {
    #[serde(rename = "1h")]
    The1H,

    #[serde(rename = "5m")]
    The5M,
}

/// Container identifier for reuse across requests.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Container {
    ContainerParams(ContainerParams),

    PurpleString(String),
}

/// Container parameters with skills to be loaded.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContainerParams {
    /// Container id
    pub id: Option<String>,

    /// List of skills to load in the container
    pub skills: Option<Vec<SkillParams>>,
}

/// Specification for a skill to be loaded in a container (request model).
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct SkillParams {
    /// Skill ID
    pub skill_id: String,

    /// Type of skill - either 'anthropic' (built-in) or 'custom' (user-defined)
    #[serde(rename = "type")]
    pub skill_params_type: SkillType,

    /// Skill version or 'latest' for most recent version
    pub version: Option<String>,
}

/// Type of skill - either 'anthropic' (built-in) or 'custom' (user-defined)
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum SkillType {
    Anthropic,

    Custom,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct InputMessage {
    pub content: MessageContent,

    pub role: Role,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum MessageContent {
    InputContentBlockArray(Vec<InputContentBlock>),

    PurpleString(String),
}

/// Regular text content.
///
/// Image content specified directly as base64 data or as a reference via a URL.
///
/// Document content, either specified directly as base64 data, as text, or as a reference
/// via a URL.
///
/// A search result block containing source, title, and content from search operations.
///
/// A block specifying internal thinking by the model.
///
/// A block specifying internal, redacted thinking by the model.
///
/// A block indicating a tool use by the model.
///
/// A block specifying the results of a tool use by the model.
///
/// A content block that represents a file to be uploaded to the container
/// Files uploaded via this block will be available in the container's input directory.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct InputContentBlock {
    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    pub citations: Option<Citations>,

    pub text: Option<String>,

    #[serde(rename = "type")]
    pub input_content_block_type: InputContentBlockType,

    pub source: Option<SourceUnion>,

    /// Configures the transformations the server applies to this image before the model observes
    /// it. Each key names a condition the server transforms images for; its value selects the
    /// transformation applied. Omitted keys keep their default behavior, and an empty object is
    /// equivalent to omitting the field.
    pub transformations: Option<RequestImageTransformations>,

    pub context: Option<String>,

    pub title: Option<String>,

    pub content: Option<Content>,

    /// The `signature` value of this thinking block, exactly as returned by the API in a
    /// previous response. Used to verify that the block was generated by Claude.
    ///
    /// Thinking blocks must be passed back unmodified and in their original order; a modified
    /// block results in a 400 `invalid_request_error`.
    pub signature: Option<String>,

    /// The `thinking` text of this block as returned by the API.
    pub thinking: Option<String>,

    /// The `data` value of this redacted thinking block, exactly as returned by the API in a
    /// previous response. Opaque and encrypted; pass it back unchanged.
    pub data: Option<String>,

    pub caller: Option<Caller>,

    pub id: Option<String>,

    #[schema(value_type = Option<Object>)]
    pub input: Option<HashMap<String, Option<serde_json::Value>>>,

    pub name: Option<String>,

    /// For a toolset member tool_use, the toolset family this member belongs to.
    ///
    /// For a toolset member tool_result, the toolset family of the paired tool_use.
    pub toolset_name: Option<String>,

    pub is_error: Option<bool>,

    pub tool_use_id: Option<String>,

    pub file_id: Option<String>,
}

/// Tool invocation directly from the model.
///
/// Tool invocation generated by a server-side tool.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Caller {
    #[serde(rename = "type")]
    pub caller_type: CallerType,

    pub tool_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum CallerType {
    #[serde(rename = "code_execution_20250825")]
    CodeExecution20250825,

    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,

    Direct,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Citations {
    RequestCitationsConfig(RequestCitationsConfig),

    RequestLocationCitationArray(Vec<RequestLocationCitation>),
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestLocationCitation {
    /// The full text of the cited block range, concatenated.
    ///
    /// Always equals the contents of `content[start_block_index:end_block_index]` joined
    /// together. The text block is the minimal citable unit; this field is never a substring of
    /// a single block. Not counted toward output tokens, and not counted toward input tokens
    /// when sent back in subsequent turns.
    pub cited_text: String,

    pub document_index: Option<i64>,

    pub document_title: Option<String>,

    pub end_char_index: Option<i64>,

    pub start_char_index: Option<i64>,

    #[serde(rename = "type")]
    pub request_location_citation_type: CitationType,

    pub end_page_number: Option<i64>,

    pub start_page_number: Option<i64>,

    /// Exclusive 0-based end index of the cited block range in the source's `content` array.
    ///
    /// Always greater than `start_block_index`; a single-block citation has `end_block_index =
    /// start_block_index + 1`.
    pub end_block_index: Option<i64>,

    /// 0-based index of the first cited block in the source's `content` array.
    pub start_block_index: Option<i64>,

    pub encrypted_index: Option<String>,

    pub title: Option<String>,

    pub url: Option<String>,

    /// 0-based index of the cited search result among all `search_result` content blocks in the
    /// request, in the order they appear across messages and tool results.
    ///
    /// Counted separately from `document_index`; server-side web search results are not included
    /// in this count.
    pub search_result_index: Option<i64>,

    pub source: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum CitationType {
    #[serde(rename = "char_location")]
    CharLocation,

    #[serde(rename = "content_block_location")]
    ContentBlockLocation,

    #[serde(rename = "page_location")]
    PageLocation,

    #[serde(rename = "search_result_location")]
    SearchResultLocation,

    #[serde(rename = "web_search_result_location")]
    WebSearchResultLocation,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestCitationsConfig {
    pub enabled: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Content {
    BlockArray(Vec<Block>),

    PurpleString(String),

    Request(Request),
}

/// Regular text content.
///
/// Image content specified directly as base64 data or as a reference via a URL.
///
/// A search result block containing source, title, and content from search operations.
///
/// Document content, either specified directly as base64 data, as text, or as a reference
/// via a URL.
///
/// Tool reference block that can be included in tool_result content.
///
/// The caller's browser state after a browser toolset member call —
/// the full inventory of open tabs, which tab is active, and any side
/// effects (tabs opened, download state changes) the call produced.
///
/// At most one per `tool_result`, only on a non-error result answering a
/// browser toolset member `tool_use`. The server renders the
/// model-visible text from it; the model never sees the raw fields.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Block {
    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    pub citations: Option<Citations>,

    pub text: Option<String>,

    #[serde(rename = "type")]
    pub block_type: WebSearchToolResultBlockItemType,

    pub source: Option<SourceUnion>,

    /// Configures the transformations the server applies to this image before the model observes
    /// it. Each key names a condition the server transforms images for; its value selects the
    /// transformation applied. Omitted keys keep their default behavior, and an empty object is
    /// equivalent to omitting the field.
    pub transformations: Option<RequestImageTransformations>,

    pub content: Option<Vec<RequestTextBlock>>,

    pub title: Option<String>,

    pub context: Option<String>,

    pub tool_name: Option<String>,

    /// Tabs opened and download state changes during this call. "Nothing to report" is expressed
    /// by omitting the field, never by an empty list.
    pub state_changes: Option<Vec<BrowserStateChange>>,

    /// All tabs open in the browser after this call — the full inventory, not a delta. May be
    /// empty. Whenever non-empty, exactly one entry carries `active: true`.
    pub tabs: Option<Vec<BrowserStateTabEntry>>,

    pub encrypted_content: Option<String>,

    pub page_age: Option<String>,

    pub url: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum WebSearchToolResultBlockItemType {
    #[serde(rename = "browser_state")]
    BrowserState,

    Document,

    Image,

    #[serde(rename = "search_result")]
    SearchResult,

    Text,

    #[serde(rename = "tool_reference")]
    ToolReference,

    #[serde(rename = "web_search_result")]
    WebSearchResult,
}

/// Regular text content.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestTextBlock {
    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    pub citations: Option<Vec<RequestLocationCitation>>,

    pub text: String,

    #[serde(rename = "type")]
    pub request_text_block_type: SystemType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum SystemType {
    Text,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum SourceUnion {
    PurpleString(String),

    Source(Source),
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Source {
    pub data: Option<String>,

    pub media_type: Option<Base64ImageSourceMediaType>,

    #[serde(rename = "type")]
    pub source_type: Base64ImageSourceType,

    pub url: Option<String>,

    pub file_id: Option<String>,

    pub content: Option<Base64ImageSourceContent>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum Base64ImageSourceContent {
    ContentBlockSourceContentItemArray(Vec<ContentBlockSourceContentItem>),

    PurpleString(String),
}

/// Regular text content.
///
/// Image content specified directly as base64 data or as a reference via a URL.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContentBlockSourceContentItem {
    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    pub citations: Option<Vec<RequestLocationCitation>>,

    pub text: Option<String>,

    #[serde(rename = "type")]
    pub content_block_source_content_item_type: ContentBlockSourceContentItemType,

    pub source: Option<SourceSource>,

    /// Configures the transformations the server applies to this image before the model observes
    /// it. Each key names a condition the server transforms images for; its value selects the
    /// transformation applied. Omitted keys keep their default behavior, and an empty object is
    /// equivalent to omitting the field.
    pub transformations: Option<RequestImageTransformations>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ContentBlockSourceContentItemType {
    Image,

    Text,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct SourceSource {
    pub data: Option<String>,

    pub media_type: Option<PurpleMediaType>,

    #[serde(rename = "type")]
    pub source_type: PurpleType,

    pub url: Option<String>,

    pub file_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub enum PurpleMediaType {
    #[serde(rename = "image/gif")]
    ImageGif,

    #[serde(rename = "image/jpeg")]
    ImageJpeg,

    #[serde(rename = "image/png")]
    ImagePng,

    #[serde(rename = "image/webp")]
    ImageWebp,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum PurpleType {
    Base64,

    File,

    Url,
}

/// Configures the transformations the server applies to this image before the model observes
/// it. Each key names a condition the server transforms images for; its value selects the
/// transformation applied. Omitted keys keep their default behavior, and an empty object is
/// equivalent to omitting the field.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestImageTransformations {
    /// What the server does when this image exceeds the model's maximum image size. `"downsize"`
    /// (the default) scales the image down to fit, which changes the dimensions the model
    /// observes without telling you. `"error"` instead rejects the request with a 400 error
    /// naming the image's dimensions and the largest dimensions that fit, so you can scale the
    /// image deliberately — your image is never silently scaled down.
    pub oversized_image: Option<OversizedImage>,
}

/// What the server does when this image exceeds the model's maximum image size. `"downsize"`
/// (the default) scales the image down to fit, which changes the dimensions the model
/// observes without telling you. `"error"` instead rejects the request with a 400 error
/// naming the image's dimensions and the largest dimensions that fit, so you can scale the
/// image deliberately — your image is never silently scaled down.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum OversizedImage {
    Downsize,

    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub enum Base64ImageSourceMediaType {
    #[serde(rename = "application/pdf")]
    ApplicationPdf,

    #[serde(rename = "image/gif")]
    ImageGif,

    #[serde(rename = "image/jpeg")]
    ImageJpeg,

    #[serde(rename = "image/png")]
    ImagePng,

    #[serde(rename = "image/webp")]
    ImageWebp,

    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Base64ImageSourceType {
    Base64,

    Content,

    File,

    Text,

    Url,
}

/// A tab this call's execution opened that remains open at its end —
/// the creation delta of the `tabs` inventory, not an event log.
///
/// Carries only the `tab_id`; the tab's `title` and `url` live on its
/// `tabs` entry, which must include the same `tab_id`. A tab opened
/// during a failed call gets no deferred `tab_opened`; it simply appears
/// in the next result's `tabs` inventory.
///
/// A file download that started during this call.
///
/// A file download that finished during this call, reported with the
/// same `download_id` as its `download_started` — or without a prior
/// `download_started`, when the download finished during the call that
/// started it (at most one state change per `download_id` per result).
///
/// A file download that failed — or was cancelled — during this call.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserStateChange {
    /// The `tab_id` of the opened tab, present in `tabs`.
    pub tab_id: Option<String>,

    #[serde(rename = "type")]
    pub browser_state_change_type: StateChangeType,

    /// The caller-assigned identifier for this download, stable across the state changes
    /// reporting it.
    pub download_id: Option<String>,

    /// The final post-redirect URL the download was served from.
    pub url: Option<String>,

    /// Where the executor saved the file, on the executor's filesystem. Only included when
    /// another tool in the same environment can read the file at that path.
    pub path: Option<String>,

    /// The completed download's size.
    pub size_bytes: Option<i64>,

    /// The failure or cancellation detail, when known.
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum StateChangeType {
    #[serde(rename = "download_completed")]
    DownloadCompleted,

    #[serde(rename = "download_failed")]
    DownloadFailed,

    #[serde(rename = "download_started")]
    DownloadStarted,

    #[serde(rename = "tab_opened")]
    TabOpened,
}

/// One open browser tab reported in a `browser_state` block's `tabs`
/// inventory.
///
/// `tab_id` is the caller-assigned identifier for the tab; `title` and
/// `url` describe the page the tab is currently showing and may be empty
/// strings (a blank tab legitimately has both empty). `active` marks the
/// tab that is active after this call; whenever `tabs` is non-empty,
/// exactly one entry is marked.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserStateTabEntry {
    /// Whether this tab is the active tab after this call. Whenever `tabs` is non-empty, exactly
    /// one entry is marked `active: true`.
    pub active: Option<bool>,

    /// The caller-assigned identifier for this tab, unique within the inventory.
    pub tab_id: String,

    /// The title of the page the tab is showing. May be empty.
    pub title: String,

    /// The URL of the page the tab is showing. May be empty.
    pub url: String,
}

/// Code execution result with encrypted stdout for PFC + web_search results.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Request {
    pub error_code: Option<ToolResultErrorCode>,

    #[serde(rename = "type")]
    pub request_type: RequestWebSearchToolResultErrorType,

    pub content: Option<RequestWebSearchToolResultErrorContent>,

    /// ISO 8601 timestamp when the content was retrieved
    pub retrieved_at: Option<String>,

    /// Fetched content URL
    pub url: Option<String>,

    pub return_code: Option<i64>,

    pub stderr: Option<String>,

    pub stdout: Option<String>,

    pub encrypted_stdout: Option<String>,

    pub error_message: Option<String>,

    pub file_type: Option<FileType>,

    pub num_lines: Option<i64>,

    pub start_line: Option<i64>,

    pub total_lines: Option<i64>,

    pub is_file_update: Option<bool>,

    pub lines: Option<Vec<String>>,

    pub new_lines: Option<i64>,

    pub new_start: Option<i64>,

    pub old_lines: Option<i64>,

    pub old_start: Option<i64>,

    pub tool_references: Option<Vec<RequestToolReferenceBlock>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum RequestWebSearchToolResultErrorContent {
    PurpleString(String),

    RequestCodeExecutionOutputBlockArray(Vec<RequestCodeExecutionOutputBlock>),

    RequestDocumentBlock(RequestDocumentBlock),
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestCodeExecutionOutputBlock {
    pub file_id: String,

    #[serde(rename = "type")]
    pub request_code_execution_output_block_type: FluffyType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum FluffyType {
    #[serde(rename = "bash_code_execution_output")]
    BashCodeExecutionOutput,

    #[serde(rename = "code_execution_output")]
    CodeExecutionOutput,
}

/// Document content, either specified directly as base64 data, as text, or as a reference
/// via a URL.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestDocumentBlock {
    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    pub citations: Option<RequestCitationsConfig>,

    pub context: Option<String>,

    pub source: RequestDocumentBlockSource,

    pub title: Option<String>,

    #[serde(rename = "type")]
    pub request_document_block_type: RequestDocumentBlockType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RequestDocumentBlockType {
    Document,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestDocumentBlockSource {
    pub data: Option<String>,

    pub media_type: Option<FluffyMediaType>,

    #[serde(rename = "type")]
    pub source_type: Base64ImageSourceType,

    pub content: Option<Base64ImageSourceContent>,

    pub url: Option<String>,

    pub file_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub enum FluffyMediaType {
    #[serde(rename = "application/pdf")]
    ApplicationPdf,

    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolResultErrorCode {
    #[serde(rename = "execution_time_exceeded")]
    ExecutionTimeExceeded,

    #[serde(rename = "file_not_found")]
    FileNotFound,

    #[serde(rename = "invalid_tool_input")]
    InvalidToolInput,

    #[serde(rename = "max_uses_exceeded")]
    MaxUsesExceeded,

    #[serde(rename = "output_file_too_large")]
    OutputFileTooLarge,

    #[serde(rename = "query_too_long")]
    QueryTooLong,

    #[serde(rename = "request_too_large")]
    RequestTooLarge,

    #[serde(rename = "too_many_requests")]
    TooManyRequests,

    Unavailable,

    #[serde(rename = "unsupported_content_type")]
    UnsupportedContentType,

    #[serde(rename = "url_not_accessible")]
    UrlNotAccessible,

    #[serde(rename = "url_not_allowed")]
    UrlNotAllowed,

    #[serde(rename = "url_not_in_prior_context")]
    UrlNotInPriorContext,

    #[serde(rename = "url_too_long")]
    UrlTooLong,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum FileType {
    Image,

    Pdf,

    Text,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RequestWebSearchToolResultErrorType {
    #[serde(rename = "bash_code_execution_result")]
    BashCodeExecutionResult,

    #[serde(rename = "bash_code_execution_tool_result_error")]
    BashCodeExecutionToolResultError,

    #[serde(rename = "code_execution_result")]
    CodeExecutionResult,

    #[serde(rename = "code_execution_tool_result_error")]
    CodeExecutionToolResultError,

    #[serde(rename = "encrypted_code_execution_result")]
    EncryptedCodeExecutionResult,

    #[serde(rename = "text_editor_code_execution_create_result")]
    TextEditorCodeExecutionCreateResult,

    #[serde(rename = "text_editor_code_execution_str_replace_result")]
    TextEditorCodeExecutionStrReplaceResult,

    #[serde(rename = "text_editor_code_execution_tool_result_error")]
    TextEditorCodeExecutionToolResultError,

    #[serde(rename = "text_editor_code_execution_view_result")]
    TextEditorCodeExecutionViewResult,

    #[serde(rename = "tool_search_tool_result_error")]
    ToolSearchToolResultError,

    #[serde(rename = "tool_search_tool_search_result")]
    ToolSearchToolSearchResult,

    #[serde(rename = "web_fetch_result")]
    WebFetchResult,

    #[serde(rename = "web_fetch_tool_result_error")]
    WebFetchToolResultError,

    #[serde(rename = "web_search_tool_result_error")]
    WebSearchToolResultError,
}

/// Tool reference block that can be included in tool_result content.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RequestToolReferenceBlock {
    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    pub tool_name: String,

    #[serde(rename = "type")]
    pub request_tool_reference_block_type: ToolReferenceType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolReferenceType {
    #[serde(rename = "tool_reference")]
    ToolReference,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum InputContentBlockType {
    #[serde(rename = "bash_code_execution_tool_result")]
    BashCodeExecutionToolResult,

    #[serde(rename = "code_execution_tool_result")]
    CodeExecutionToolResult,

    #[serde(rename = "container_upload")]
    ContainerUpload,

    Document,

    Image,

    #[serde(rename = "redacted_thinking")]
    RedactedThinking,

    #[serde(rename = "search_result")]
    SearchResult,

    #[serde(rename = "server_tool_use")]
    ServerToolUse,

    Text,

    #[serde(rename = "text_editor_code_execution_tool_result")]
    TextEditorCodeExecutionToolResult,

    Thinking,

    #[serde(rename = "tool_result")]
    ToolResult,

    #[serde(rename = "tool_search_tool_result")]
    ToolSearchToolResult,

    #[serde(rename = "tool_use")]
    ToolUse,

    #[serde(rename = "web_fetch_tool_result")]
    WebFetchToolResult,

    #[serde(rename = "web_search_tool_result")]
    WebSearchToolResult,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    Assistant,

    System,

    User,
}

/// An object describing metadata about the request.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Metadata {
    /// An external identifier for the user who is associated with the request.
    ///
    /// This should be a uuid, hash value, or other opaque identifier. Anthropic may use this id
    /// to help detect abuse. Do not include any identifying information such as name, email
    /// address, or phone number.
    pub user_id: Option<String>,
}

/// Configuration options for the model's output, such as the output format.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct OutputConfig {
    /// How much effort the model should put into its response. Higher effort levels may result
    /// in more thorough analysis but take longer.
    ///
    /// Valid values are `low`, `medium`, `high`, `xhigh`, or `max`.
    pub effort: Option<EffortLevel>,

    /// A schema to specify Claude's output format in responses. See [structured
    /// outputs](https://platform.claude.com/docs/en/build-with-claude/structured-outputs)
    pub format: Option<JsonOutputFormat>,
}

/// All possible effort levels.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum EffortLevel {
    High,

    Low,

    Max,

    Medium,

    Xhigh,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct JsonOutputFormat {
    /// The JSON schema of the format
    #[schema(value_type = Object)]
    pub schema: HashMap<String, Option<serde_json::Value>>,

    #[serde(rename = "type")]
    pub json_output_format_type: JsonOutputFormatType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum JsonOutputFormatType {
    #[serde(rename = "json_schema")]
    JsonSchema,
}

/// Determines whether to use priority capacity (if available) or standard capacity for this
/// request.
///
/// Anthropic offers different levels of service for your API requests. See
/// [service-tiers](https://platform.claude.com/docs/en/api/service-tiers) for details.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ServiceTier {
    Auto,

    #[serde(rename = "standard_only")]
    StandardOnly,
}

/// System prompt.
///
/// A system prompt is a way of providing context and instructions to Claude, such as
/// specifying a particular goal or role. See our [guide to system
/// prompts](https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices#give-claude-a-role).
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum System {
    PurpleString(String),

    RequestTextBlockArray(Vec<RequestTextBlock>),
}

/// Configuration for enabling Claude's extended thinking.
///
/// When enabled, responses include `thinking` content blocks showing Claude's thinking
/// process before the final answer. Requires a minimum budget of 1,024 tokens and counts
/// towards your `max_tokens` limit.
///
/// See [extended
/// thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking) for
/// details.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Thinking {
    /// Determines how many tokens Claude can use for its internal reasoning process. Larger
    /// budgets can enable more thorough analysis for complex problems, improving response
    /// quality.
    ///
    /// Must be ≥1024 and less than `max_tokens`.
    ///
    /// See [extended
    /// thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking) for
    /// details.
    pub budget_tokens: Option<i64>,

    /// Controls how thinking content appears in the response. When set to `summarized`, thinking
    /// is returned normally. When set to `omitted`, thinking content is redacted but a signature
    /// is returned for multi-turn continuity. Defaults to `summarized`.
    pub display: Option<ThinkingDisplayMode>,

    #[serde(rename = "type")]
    pub thinking_type: ThinkingType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ThinkingDisplayMode {
    Omitted,

    Summarized,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ThinkingType {
    Adaptive,

    Disabled,

    Enabled,
}

/// How the model should use the provided tools. The model can use a specific tool, any
/// available tool, decide by itself, or not use tools at all.
///
/// The model will automatically decide whether to use tools.
///
/// The model will use any available tools.
///
/// The model will use the specified tool with `tool_choice.name`.
///
/// The model will not be allowed to use tools.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ToolChoice {
    /// Whether to disable parallel tool use.
    ///
    /// Defaults to `false`. If set to `true`, the model will output at most one tool use.
    ///
    /// Whether to disable parallel tool use.
    ///
    /// Defaults to `false`. If set to `true`, the model will output exactly one tool use.
    pub disable_parallel_tool_use: Option<bool>,

    #[serde(rename = "type")]
    pub tool_choice_type: ToolChoiceType,

    /// The name of the tool to use.
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ToolChoiceType {
    Any,

    Auto,

    Tool,

    #[serde(rename = "none")]
    TypeNone,
}

/// Code execution tool with REPL state persistence (daemon mode + gVisor checkpoint).
///
/// Code execution tool with REPL state persistence.
///
/// The browser toolset: a single ``tools[]`` entry (carrying no
/// ``name``) that declares the browser tool family. The model is served
/// the family's tool with any members disabled via ``configs`` removed
/// from its schema.
///
/// The computer toolset: a single ``tools[]`` entry (carrying no
/// ``name``) that declares the computer tool family. The model is
/// served the family's tool with any members disabled via ``configs``
/// removed from its schema. Every member is enabled by default, zoom
/// included. The single-tool options ``display_number`` and
/// ``enable_zoom`` are not fields of a toolset entry — it carries only
/// ``type``, ``configs``, and ``cache_control``; zoom is controlled
/// via ``configs.zoom.enabled``.
///
/// Web fetch tool with use_cache parameter for bypassing cached content.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Tool {
    pub allowed_callers: Option<Vec<AllowedCaller>>,

    /// Create a cache control breakpoint at this content block.
    pub cache_control: Option<CacheControlEphemeral>,

    /// If true, tool will not be included in initial system prompt. Only loaded when returned
    /// via tool_reference from tool search.
    pub defer_loading: Option<bool>,

    /// Description of what this tool does.
    ///
    /// Tool descriptions should be as detailed as possible. The more information that the model
    /// has about what the tool is and how to use it, the better it will perform. You can use
    /// natural language descriptions to reinforce important aspects of the tool input JSON
    /// schema.
    pub description: Option<String>,

    /// Enable eager input streaming for this tool. When true, tool input parameters will be
    /// streamed incrementally as they are generated, and types will be inferred on-the-fly
    /// rather than buffering the full JSON output. When false, streaming is disabled for this
    /// tool even if the fine-grained-tool-streaming beta is active. When null (default), uses
    /// the default behavior based on beta headers.
    pub eager_input_streaming: Option<bool>,

    #[schema(value_type = Option<Vec<Object>>)]
    pub input_examples: Option<Vec<HashMap<String, Option<serde_json::Value>>>>,

    /// [JSON schema](https://json-schema.org/draft/2020-12) for this tool's input.
    ///
    /// This defines the shape of the `input` that your tool accepts and that the model will
    /// produce.
    pub input_schema: Option<InputSchema>,

    /// Name of the tool.
    ///
    /// This is how the tool will be called by the model and in `tool_use` blocks.
    pub name: Option<String>,

    /// When true, guarantees schema validation on tool names and inputs
    pub strict: Option<bool>,

    #[serde(rename = "type")]
    pub tool_type: Option<Type>,

    /// Sparse per-member overrides, keyed by member name. Absent, null, and {} are equivalent; a
    /// member's defaults apply wherever its key is absent.
    pub configs: Option<ErToolsetConfigs>,

    /// Maximum number of characters to display when viewing a file. If not specified, defaults
    /// to displaying the full file.
    pub max_characters: Option<i64>,

    /// If provided, only these domains will be included in results. Cannot be used alongside
    /// `blocked_domains`.
    ///
    /// List of domains to allow fetching from
    pub allowed_domains: Option<Vec<String>>,

    /// If provided, these domains will never appear in results. Cannot be used alongside
    /// `allowed_domains`.
    ///
    /// List of domains to block fetching from
    pub blocked_domains: Option<Vec<String>>,

    /// Maximum number of times the tool can be used in the API request.
    pub max_uses: Option<i64>,

    /// Parameters for the user's location. Used to provide more relevant search results.
    pub user_location: Option<UserLocation>,

    /// Citations configuration for fetched documents. Citations are disabled by default.
    pub citations: Option<RequestCitationsConfig>,

    /// Maximum number of tokens used by including web page text content in the context. The
    /// limit is approximate and does not apply to binary content such as PDFs.
    pub max_content_tokens: Option<i64>,

    /// Whether to use cached content. Set to false to bypass the cache and fetch fresh content.
    /// Only set to false when the user explicitly requests fresh content or when fetching
    /// rapidly-changing sources.
    pub use_cache: Option<bool>,

    /// How this tool's result blocks appear in the API response when the result was consumed by
    /// a completed code_execution call in the same turn. 'full' returns the complete content
    /// (default). 'excluded' drops the nested server_tool_use and result block pair entirely.
    /// Results from direct calls, or from code_execution calls that paused before completing,
    /// are always returned in full so they can be sent back on the next turn.
    pub response_inclusion: Option<ResponseInclusion>,
}

/// Specifies who can invoke a tool.
///
/// Values:
/// direct: The model can call this tool directly.
/// code_execution_20250825: The tool can be called from the code execution environment
/// (v1).
/// code_execution_20260120: The tool can be called from the code execution environment (v2
/// with persistence).
/// code_execution_20260521: The tool can be called from the code execution environment (v2
/// with persistence).
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum AllowedCaller {
    #[serde(rename = "code_execution_20250825")]
    CodeExecution20250825,

    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,

    #[serde(rename = "code_execution_20260521")]
    CodeExecution20260521,

    Direct,
}

/// Per-member configuration for ``browser_toolset_20260801``: one
/// optional field per member tool, keyed by the member name — the same
/// name the member's ``tool_use`` blocks carry. Every member is an
/// accepted key, and a member's defaults apply wherever its key is
/// absent. Unknown keys are rejected: the field set is this toolset
/// version's complete member set.
///
/// Per-member configuration for ``computer_toolset_20260801``: one
/// optional field per member tool, keyed by the member name — the same
/// name the member's ``tool_use`` blocks carry. Every member is an
/// accepted key, and a member's defaults apply wherever its key is
/// absent. Unknown keys are rejected: the field set is this toolset
/// version's complete member set.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErToolsetConfigs {
    pub close_tab: Option<BrowserCloseTabConfig>,

    pub double_click: Option<ErDoubleClickConfig>,

    pub file_upload: Option<BrowserFileUploadConfig>,

    pub find: Option<BrowserFindConfig>,

    pub form_input: Option<BrowserFormInputConfig>,

    pub get_page_text: Option<BrowserGetPageTextConfig>,

    pub hold_key: Option<ErHoldKeyConfig>,

    pub hover: Option<BrowserHoverConfig>,

    pub javascript_exec: Option<BrowserJavascriptExecConfig>,

    pub key: Option<ErKeyConfig>,

    pub left_click: Option<ErLeftClickConfig>,

    pub left_click_drag: Option<ErLeftClickDragConfig>,

    pub left_mouse_down: Option<ErLeftMouseDownConfig>,

    pub left_mouse_up: Option<ErLeftMouseUpConfig>,

    pub list_tabs: Option<BrowserListTabsConfig>,

    pub middle_click: Option<ErMiddleClickConfig>,

    pub mouse_move: Option<ErMouseMoveConfig>,

    pub navigate: Option<BrowserNavigateConfig>,

    pub new_tab: Option<BrowserNewTabConfig>,

    pub read_console: Option<BrowserReadConsoleConfig>,

    pub read_network: Option<BrowserReadNetworkConfig>,

    pub read_page: Option<BrowserReadPageConfig>,

    pub right_click: Option<ErRightClickConfig>,

    pub screenshot: Option<ErScreenshotConfig>,

    pub scroll: Option<ErScrollConfig>,

    pub scroll_to: Option<BrowserScrollToConfig>,

    pub switch_tab: Option<BrowserSwitchTabConfig>,

    pub triple_click: Option<ErTripleClickConfig>,

    #[serde(rename = "type")]
    pub er_toolset_configs_type: Option<ErTypeConfig>,

    pub wait: Option<ErWaitConfig>,

    pub zoom: Option<ErZoomConfig>,

    pub cursor_position: Option<ComputerCursorPositionConfig>,
}

/// ``close_tab``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserCloseTabConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``cursor_position``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ComputerCursorPositionConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``double_click``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErDoubleClickConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``type``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErTypeConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``file_upload``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserFileUploadConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``find``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserFindConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``form_input``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserFormInputConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``get_page_text``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserGetPageTextConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``hold_key``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErHoldKeyConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``hover``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserHoverConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``javascript_exec``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserJavascriptExecConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``key``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErKeyConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``left_click``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErLeftClickConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``left_click_drag``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErLeftClickDragConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``left_mouse_down``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErLeftMouseDownConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``left_mouse_up``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErLeftMouseUpConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``list_tabs``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserListTabsConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``middle_click``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErMiddleClickConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``mouse_move``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErMouseMoveConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``navigate``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserNavigateConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``new_tab``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserNewTabConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``read_console``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserReadConsoleConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``read_network``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserReadNetworkConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``read_page``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserReadPageConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``right_click``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErRightClickConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``screenshot``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErScreenshotConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``scroll``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErScrollConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``scroll_to``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserScrollToConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``switch_tab``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct BrowserSwitchTabConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``triple_click``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErTripleClickConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``wait``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErWaitConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// ``zoom``'s config overrides.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErZoomConfig {
    /// Defer loading for this member. Must resolve to the same value on every enabled member of
    /// the toolset.
    pub defer_loading: Option<bool>,

    /// Whether this member is offered to the model. Default is per member, per the toolset's
    /// documentation. A member whose enabled resolves false is withheld from the served schema.
    pub enabled: Option<bool>,
}

/// [JSON schema](https://json-schema.org/draft/2020-12) for this tool's input.
///
/// This defines the shape of the `input` that your tool accepts and that the model will
/// produce.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct InputSchema {
    #[schema(value_type = Option<Object>)]
    pub properties: Option<HashMap<String, Option<serde_json::Value>>>,

    pub required: Option<Vec<String>>,

    #[serde(rename = "type")]
    pub input_schema_type: InputSchemaType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum InputSchemaType {
    Object,
}

/// How this tool's result blocks appear in the API response when the result was consumed by
/// a completed code_execution call in the same turn. 'full' returns the complete content
/// (default). 'excluded' drops the nested server_tool_use and result block pair entirely.
/// Results from direct calls, or from code_execution calls that paused before completing,
/// are always returned in full so they can be sent back on the next turn.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResponseInclusion {
    Excluded,

    Full,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum Type {
    #[serde(rename = "bash_20250124")]
    Bash20250124,

    #[serde(rename = "browser_toolset_20260801")]
    BrowserToolset20260801,

    #[serde(rename = "code_execution_20250522")]
    CodeExecution20250522,

    #[serde(rename = "code_execution_20250825")]
    CodeExecution20250825,

    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,

    #[serde(rename = "code_execution_20260521")]
    CodeExecution20260521,

    #[serde(rename = "computer_toolset_20260801")]
    ComputerToolset20260801,

    Custom,

    #[serde(rename = "memory_20250818")]
    Memory20250818,

    #[serde(rename = "text_editor_20250124")]
    TextEditor20250124,

    #[serde(rename = "text_editor_20250429")]
    TextEditor20250429,

    #[serde(rename = "text_editor_20250728")]
    TextEditor20250728,

    #[serde(rename = "tool_search_tool_bm25")]
    ToolSearchToolBm25,

    #[serde(rename = "tool_search_tool_bm25_20251119")]
    ToolSearchToolBm2520251119,

    #[serde(rename = "tool_search_tool_regex")]
    ToolSearchToolRegex,

    #[serde(rename = "tool_search_tool_regex_20251119")]
    ToolSearchToolRegex20251119,

    #[serde(rename = "web_fetch_20250910")]
    WebFetch20250910,

    #[serde(rename = "web_fetch_20260209")]
    WebFetch20260209,

    #[serde(rename = "web_fetch_20260309")]
    WebFetch20260309,

    #[serde(rename = "web_fetch_20260318")]
    WebFetch20260318,

    #[serde(rename = "web_search_20250305")]
    WebSearch20250305,

    #[serde(rename = "web_search_20260209")]
    WebSearch20260209,

    #[serde(rename = "web_search_20260318")]
    WebSearch20260318,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct UserLocation {
    /// The city of the user.
    pub city: Option<String>,

    /// The two letter [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of
    /// the user.
    pub country: Option<String>,

    /// The region of the user.
    pub region: Option<String>,

    /// The [IANA timezone](https://nodatime.org/TimeZones) of the user.
    pub timezone: Option<String>,

    #[serde(rename = "type")]
    pub user_location_type: UserLocationType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum UserLocationType {
    Approximate,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Message {
    /// Information about the container used in this request.
    ///
    /// This will be non-null if a container tool (e.g. code execution) was used.
    pub container: Option<Container>,

    /// Content generated by the model.
    ///
    /// This is an array of content blocks, each of which has a `type` that determines its
    /// shape.
    ///
    /// Example:
    ///
    /// ```json
    /// [{"type": "text", "text": "Hi, I'm Claude."}]
    /// ```
    ///
    /// If the request input `messages` ended with an `assistant` turn, then the response
    /// `content` will continue directly from that last turn. You can use this to constrain the
    /// model's output.
    ///
    /// For example, if the input `messages` were:
    /// ```json
    /// [
    /// {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C)
    /// Sun"},
    /// {"role": "assistant", "content": "The best answer is ("}
    /// ]
    /// ```
    ///
    /// Then the response `content` might be:
    ///
    /// ```json
    /// [{"type": "text", "text": "B)"}]
    /// ```
    pub content: Vec<ContentBlock>,

    /// Unique object identifier.
    ///
    /// The format and length of IDs may change over time.
    pub id: String,

    pub model: String,

    /// Conversational role of the generated message.
    ///
    /// This will always be `"assistant"`.
    pub role: Role,

    /// Structured information about why model output stopped.
    ///
    /// This is `null` when the `stop_reason` has no additional detail to report.
    pub stop_details: Option<RefusalStopDetails>,

    /// The reason that we stopped.
    ///
    /// This may be one the following values:
    /// * `"end_turn"`: the model reached a natural stopping point
    /// * `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
    /// * `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
    /// * `"tool_use"`: the model invoked one or more tools
    /// * `"pause_turn"`: we paused a long-running turn. You may provide the response back as-is
    /// in a subsequent request to let the model continue.
    /// * `"refusal"`: when streaming classifiers intervene to handle potential policy violations
    /// * `"model_context_window_exceeded"`: we exceeded the model's context window
    ///
    /// In non-streaming mode this value is always non-null. In streaming mode, it is null in the
    /// `message_start` event and non-null otherwise.
    pub stop_reason: Option<StopReason>,

    /// Which custom stop sequence was generated, if any.
    ///
    /// This value will be a non-null string if one of your custom stop sequences was generated.
    pub stop_sequence: Option<String>,

    /// Object type.
    ///
    /// For Messages, this is always `"message"`.
    #[serde(rename = "type")]
    pub message_type: MessageType,

    /// Billing and rate-limit usage.
    ///
    /// Anthropic's API bills and rate-limits by token counts, as tokens represent the underlying
    /// cost to our systems.
    ///
    /// Under the hood, the API transforms requests into a format suitable for the model. The
    /// model's output then goes through a parsing stage before becoming an API response. As a
    /// result, the token counts in `usage` will not match one-to-one with the exact visible
    /// content of an API request or response.
    ///
    /// For example, `output_tokens` will be non-zero, even for an empty string response from
    /// Claude.
    ///
    /// Total input tokens in a request is the summation of `input_tokens`,
    /// `cache_creation_input_tokens`, and `cache_read_input_tokens`.
    pub usage: Usage,
}

/// A skill that was loaded in a container (response model).
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContainerSkill {
    /// Skill ID
    pub skill_id: String,

    /// Type of skill - either 'anthropic' (built-in) or 'custom' (user-defined)
    #[serde(rename = "type")]
    pub container_skill_type: SkillType,

    /// The resolved version: a skill version ID for custom skills.
    pub version: String,
}

/// Response model for a file uploaded to the container.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContentBlock {
    /// Citations supporting the text block.
    ///
    /// The type of citation returned will depend on the type of document being cited. Citing a
    /// PDF results in `page_location`, plain text results in `char_location`, and content
    /// document results in `content_block_location`.
    pub citations: Option<Vec<ResponseLocationCitation>>,

    pub text: Option<String>,

    #[serde(rename = "type")]
    pub content_block_type: ContentBlockType,

    /// A value used to verify that this thinking block was generated by Claude when it is passed
    /// back to the API.
    ///
    /// This is an opaque field and should not be interpreted or parsed. When passing thinking
    /// blocks back to the API (required when using tools with extended thinking), pass them back
    /// exactly as received, with this field intact.
    ///
    /// See [extended
    /// thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking) for
    /// details.
    pub signature: Option<String>,

    /// The text of Claude's thinking process for this block.
    pub thinking: Option<String>,

    /// The contents of this redacted thinking block, returned when portions of the model's
    /// thinking were safety-redacted. This field is opaque and encrypted, with no readable
    /// content.
    ///
    /// Pass `redacted_thinking` blocks back to the API unchanged when continuing a multi-turn
    /// conversation.
    ///
    /// See [extended
    /// thinking](https://platform.claude.com/docs/en/build-with-claude/extended-thinking#redacted-thinking-blocks)
    /// for details.
    pub data: Option<String>,

    pub caller: Option<Caller>,

    pub id: Option<String>,

    #[schema(value_type = Option<Object>)]
    pub input: Option<HashMap<String, Option<serde_json::Value>>>,

    pub name: Option<String>,

    /// For a toolset member tool_use, the toolset family.
    pub toolset_name: Option<String>,

    pub content: Option<Content>,

    pub tool_use_id: Option<String>,

    pub file_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseLocationCitation {
    /// The full text of the cited block range, concatenated.
    ///
    /// Always equals the contents of `content[start_block_index:end_block_index]` joined
    /// together. The text block is the minimal citable unit; this field is never a substring of
    /// a single block. Not counted toward output tokens, and not counted toward input tokens
    /// when sent back in subsequent turns.
    pub cited_text: String,

    pub document_index: Option<i64>,

    pub document_title: Option<String>,

    pub end_char_index: Option<i64>,

    pub file_id: Option<String>,

    pub start_char_index: Option<i64>,

    #[serde(rename = "type")]
    pub response_location_citation_type: CitationType,

    pub end_page_number: Option<i64>,

    pub start_page_number: Option<i64>,

    /// Exclusive 0-based end index of the cited block range in the source's `content` array.
    ///
    /// Always greater than `start_block_index`; a single-block citation has `end_block_index =
    /// start_block_index + 1`.
    pub end_block_index: Option<i64>,

    /// 0-based index of the first cited block in the source's `content` array.
    pub start_block_index: Option<i64>,

    pub encrypted_index: Option<String>,

    pub title: Option<String>,

    pub url: Option<String>,

    /// 0-based index of the cited search result among all `search_result` content blocks in the
    /// request, in the order they appear across messages and tool results.
    ///
    /// Counted separately from `document_index`; server-side web search results are not included
    /// in this count.
    pub search_result_index: Option<i64>,

    pub source: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseWebSearchResultBlock {
    pub encrypted_content: String,

    pub page_age: Option<String>,

    pub title: String,

    #[serde(rename = "type")]
    pub response_web_search_result_block_type: ContentType,

    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ContentType {
    #[serde(rename = "web_search_result")]
    WebSearchResult,
}

/// Code execution result with encrypted stdout for PFC + web_search results.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Response {
    pub error_code: Option<ToolResultErrorCode>,

    #[serde(rename = "type")]
    pub response_type: ResponseWebSearchToolResultErrorType,

    pub content: Option<ResponseWebSearchToolResultErrorContent>,

    /// ISO 8601 timestamp when the content was retrieved
    pub retrieved_at: Option<String>,

    /// Fetched content URL
    pub url: Option<String>,

    pub return_code: Option<i64>,

    pub stderr: Option<String>,

    pub stdout: Option<String>,

    pub encrypted_stdout: Option<String>,

    pub error_message: Option<String>,

    pub file_type: Option<FileType>,

    pub num_lines: Option<i64>,

    pub start_line: Option<i64>,

    pub total_lines: Option<i64>,

    pub is_file_update: Option<bool>,

    pub lines: Option<Vec<String>>,

    pub new_lines: Option<i64>,

    pub new_start: Option<i64>,

    pub old_lines: Option<i64>,

    pub old_start: Option<i64>,

    pub tool_references: Option<Vec<ResponseToolReferenceBlock>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(untagged)]
pub enum ResponseWebSearchToolResultErrorContent {
    PurpleString(String),

    ResponseCodeExecutionOutputBlockArray(Vec<ResponseCodeExecutionOutputBlock>),

    ResponseDocumentBlock(ResponseDocumentBlock),
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseCodeExecutionOutputBlock {
    pub file_id: String,

    #[serde(rename = "type")]
    pub response_code_execution_output_block_type: ContentTypeEnum,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ContentTypeEnum {
    #[serde(rename = "bash_code_execution_output")]
    BashCodeExecutionOutput,

    #[serde(rename = "code_execution_output")]
    CodeExecutionOutput,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseDocumentBlock {
    /// Citation configuration for the document
    pub citations: Option<ResponseCitationsConfig>,

    pub source: Source,

    /// The title of the document
    pub title: Option<String>,

    #[serde(rename = "type")]
    pub response_document_block_type: ResponseDocumentBlockType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseCitationsConfig {
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResponseDocumentBlockType {
    Document,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub enum MediaType {
    #[serde(rename = "application/pdf")]
    ApplicationPdf,

    #[serde(rename = "text/plain")]
    TextPlain,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum SourceType {
    Base64,

    Text,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResponseWebSearchToolResultErrorType {
    #[serde(rename = "bash_code_execution_result")]
    BashCodeExecutionResult,

    #[serde(rename = "bash_code_execution_tool_result_error")]
    BashCodeExecutionToolResultError,

    #[serde(rename = "code_execution_result")]
    CodeExecutionResult,

    #[serde(rename = "code_execution_tool_result_error")]
    CodeExecutionToolResultError,

    #[serde(rename = "encrypted_code_execution_result")]
    EncryptedCodeExecutionResult,

    #[serde(rename = "text_editor_code_execution_create_result")]
    TextEditorCodeExecutionCreateResult,

    #[serde(rename = "text_editor_code_execution_str_replace_result")]
    TextEditorCodeExecutionStrReplaceResult,

    #[serde(rename = "text_editor_code_execution_tool_result_error")]
    TextEditorCodeExecutionToolResultError,

    #[serde(rename = "text_editor_code_execution_view_result")]
    TextEditorCodeExecutionViewResult,

    #[serde(rename = "tool_search_tool_result_error")]
    ToolSearchToolResultError,

    #[serde(rename = "tool_search_tool_search_result")]
    ToolSearchToolSearchResult,

    #[serde(rename = "web_fetch_result")]
    WebFetchResult,

    #[serde(rename = "web_fetch_tool_result_error")]
    WebFetchToolResultError,

    #[serde(rename = "web_search_tool_result_error")]
    WebSearchToolResultError,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ResponseToolReferenceBlock {
    pub tool_name: String,

    #[serde(rename = "type")]
    pub response_tool_reference_block_type: ToolReferenceType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ContentBlockType {
    #[serde(rename = "bash_code_execution_tool_result")]
    BashCodeExecutionToolResult,

    #[serde(rename = "code_execution_tool_result")]
    CodeExecutionToolResult,

    #[serde(rename = "container_upload")]
    ContainerUpload,

    #[serde(rename = "redacted_thinking")]
    RedactedThinking,

    #[serde(rename = "server_tool_use")]
    ServerToolUse,

    Text,

    #[serde(rename = "text_editor_code_execution_tool_result")]
    TextEditorCodeExecutionToolResult,

    Thinking,

    #[serde(rename = "tool_search_tool_result")]
    ToolSearchToolResult,

    #[serde(rename = "tool_use")]
    ToolUse,

    #[serde(rename = "web_fetch_tool_result")]
    WebFetchToolResult,

    #[serde(rename = "web_search_tool_result")]
    WebSearchToolResult,
}

/// Object type.
///
/// For Messages, this is always `"message"`.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum MessageType {
    Message,
}

/// Structured information about a refusal.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RefusalStopDetails {
    /// The policy category that triggered the refusal.
    ///
    /// `null` when the refusal doesn't map to a named category.
    pub category: Option<RefusalCategory>,

    /// Human-readable explanation of the refusal.
    ///
    /// This text is not guaranteed to be stable. `null` when no explanation is available for the
    /// category.
    pub explanation: Option<String>,

    #[serde(rename = "type")]
    pub refusal_stop_details_type: RefusalStopDetailsType,
}

/// The policy category that triggered a refusal.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RefusalCategory {
    Bio,

    Cyber,

    #[serde(rename = "frontier_llm")]
    FrontierLlm,

    #[serde(rename = "general_harms")]
    GeneralHarms,

    #[serde(rename = "reasoning_extraction")]
    ReasoningExtraction,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RefusalStopDetailsType {
    Refusal,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    #[serde(rename = "end_turn")]
    EndTurn,

    #[serde(rename = "max_tokens")]
    MaxTokens,

    #[serde(rename = "model_context_window_exceeded")]
    ModelContextWindowExceeded,

    #[serde(rename = "pause_turn")]
    PauseTurn,

    Refusal,

    #[serde(rename = "stop_sequence")]
    StopSequence,

    #[serde(rename = "tool_use")]
    ToolUse,
}

/// Billing and rate-limit usage.
///
/// Anthropic's API bills and rate-limits by token counts, as tokens represent the underlying
/// cost to our systems.
///
/// Under the hood, the API transforms requests into a format suitable for the model. The
/// model's output then goes through a parsing stage before becoming an API response. As a
/// result, the token counts in `usage` will not match one-to-one with the exact visible
/// content of an API request or response.
///
/// For example, `output_tokens` will be non-zero, even for an empty string response from
/// Claude.
///
/// Total input tokens in a request is the summation of `input_tokens`,
/// `cache_creation_input_tokens`, and `cache_read_input_tokens`.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Usage {
    /// Breakdown of cached tokens by TTL
    pub cache_creation: Option<CacheCreation>,

    /// The number of input tokens used to create the cache entry.
    pub cache_creation_input_tokens: Option<i64>,

    /// The number of input tokens read from the cache.
    pub cache_read_input_tokens: Option<i64>,

    /// The geographic region where inference was performed for this request.
    pub inference_geo: Option<String>,

    /// The number of input tokens which were used.
    pub input_tokens: i64,

    /// The number of output tokens which were used.
    pub output_tokens: i64,

    /// Breakdown of output tokens by category.
    ///
    /// `output_tokens` remains the inclusive, authoritative total used for billing.
    /// This object provides a read-only decomposition for observability — for example,
    /// how many of the billed output tokens were spent on internal reasoning that may
    /// have been summarized before being returned to you.
    pub output_tokens_details: Option<OutputTokensDetails>,

    /// The number of server tool requests.
    pub server_tool_use: Option<ServerToolUsage>,

    /// If the request used the priority, standard, or batch tier.
    pub service_tier: Option<ServiceTier>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct CacheCreation {
    /// The number of input tokens used to create the 1 hour cache entry.
    #[serde(rename = "ephemeral_1h_input_tokens")]
    pub ephemeral_1_h_input_tokens: i64,

    /// The number of input tokens used to create the 5 minute cache entry.
    #[serde(rename = "ephemeral_5m_input_tokens")]
    pub ephemeral_5_m_input_tokens: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct OutputTokensDetails {
    /// Number of output tokens the model generated as internal reasoning, including
    /// the thinking-block delimiter tokens.
    ///
    /// Reflects the raw reasoning the model produced, not the (possibly shorter)
    /// summarized thinking text returned in the response body. Computed by
    /// re-tokenizing the raw reasoning text, so it may differ from the model's exact
    /// generation count by a small number of tokens. Always ≤ `output_tokens`;
    /// `output_tokens - thinking_tokens` approximates the non-reasoning output.
    pub thinking_tokens: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ServerToolUsage {
    /// The number of web fetch tool requests.
    pub web_fetch_requests: i64,

    /// The number of web search tool requests.
    pub web_search_requests: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ListResponseModelInfo {
    pub data: Vec<ModelInfo>,

    /// First ID in the `data` list. Can be used as the `before_id` for the previous page.
    pub first_id: Option<String>,

    /// Indicates if there are more results in the requested page direction.
    pub has_more: bool,

    /// Last ID in the `data` list. Can be used as the `after_id` for the next page.
    pub last_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ModelInfo {
    /// Object mapping capability names to their support details. Keys are always present for all
    /// known capabilities.
    pub capabilities: Option<ModelCapabilities>,

    /// RFC 3339 datetime string representing the time at which the model was released. May be
    /// set to an epoch value if the release date is unknown.
    pub created_at: String,

    /// A human-readable name for the model.
    pub display_name: String,

    /// Unique model identifier.
    pub id: String,

    /// Maximum input context window size in tokens for this model.
    pub max_input_tokens: Option<i64>,

    /// Maximum value for the `max_tokens` parameter when using this model.
    pub max_tokens: Option<i64>,

    /// Object type.
    ///
    /// For Models, this is always `"model"`.
    #[serde(rename = "type")]
    pub model_info_type: Type,
}

/// Model capability information.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ModelCapabilities {
    /// Whether the model supports the Batch API.
    pub batch: CapabilitySupport,

    /// Whether the model supports citation generation.
    pub citations: CapabilitySupport,

    /// Whether the model supports code execution tools.
    pub code_execution: CapabilitySupport,

    /// Context management support and available strategies.
    pub context_management: ContextManagementCapability,

    /// Effort (reasoning_effort) support and available levels.
    pub effort: EffortCapability,

    /// Whether the model accepts image content blocks.
    pub image_input: CapabilitySupport,

    /// Whether the model accepts PDF content blocks.
    pub pdf_input: CapabilitySupport,

    /// Whether the model supports structured output / JSON mode / strict tool schemas.
    pub structured_outputs: CapabilitySupport,

    /// Thinking capability and supported type configurations.
    pub thinking: ThinkingCapability,
}

/// Whether the model supports the Batch API.
///
/// Indicates whether a capability is supported.
///
/// Whether the model supports citation generation.
///
/// Whether the model supports code execution tools.
///
/// Whether the model supports high effort level.
///
/// Whether the model supports low effort level.
///
/// Whether the model supports max effort level.
///
/// Whether the model supports medium effort level.
///
/// Whether the model accepts image content blocks.
///
/// Whether the model accepts PDF content blocks.
///
/// Whether the model supports structured output / JSON mode / strict tool schemas.
///
/// Whether the model supports thinking with type 'adaptive' (auto).
///
/// Whether the model supports thinking with type 'enabled'.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct CapabilitySupport {
    /// Whether this capability is supported by the model.
    pub supported: bool,
}

/// Context management support and available strategies.
///
/// Context management capability details.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ContextManagementCapability {
    /// Whether the clear_thinking_20251015 strategy is supported.
    pub clear_thinking_20251015: Option<CapabilitySupport>,

    /// Whether the clear_tool_uses_20250919 strategy is supported.
    pub clear_tool_uses_20250919: Option<CapabilitySupport>,

    /// Whether the compact_20260112 strategy is supported.
    pub compact_20260112: Option<CapabilitySupport>,

    /// Whether this capability is supported by the model.
    pub supported: bool,
}

/// Effort (reasoning_effort) support and available levels.
///
/// Effort (reasoning_effort) capability details.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct EffortCapability {
    /// Whether the model supports high effort level.
    pub high: CapabilitySupport,

    /// Whether the model supports low effort level.
    pub low: CapabilitySupport,

    /// Whether the model supports max effort level.
    pub max: CapabilitySupport,

    /// Whether the model supports medium effort level.
    pub medium: CapabilitySupport,

    /// Whether this capability is supported by the model.
    pub supported: bool,

    /// Whether the model supports xhigh effort level.
    pub xhigh: Option<CapabilitySupport>,
}

/// Thinking capability and supported type configurations.
///
/// Thinking capability details.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ThinkingCapability {
    /// Whether this capability is supported by the model.
    pub supported: bool,

    pub types: ThinkingTypes,
}

/// Supported thinking type configurations.
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ThinkingTypes {
    /// Whether the model supports thinking with type 'adaptive' (auto).
    pub adaptive: CapabilitySupport,

    /// Whether the model supports thinking with type 'enabled'.
    pub enabled: CapabilitySupport,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ErrorResponse {
    pub error: Error,

    pub request_id: Option<String>,

    #[serde(rename = "type")]
    pub error_response_type: ErrorResponseType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Error {
    pub message: String,

    #[serde(rename = "type")]
    pub error_type: ErrorType,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ErrorType {
    #[serde(rename = "api_error")]
    ApiError,

    #[serde(rename = "authentication_error")]
    AuthenticationError,

    #[serde(rename = "billing_error")]
    BillingError,

    #[serde(rename = "invalid_request_error")]
    InvalidRequestError,

    #[serde(rename = "not_found_error")]
    NotFoundError,

    #[serde(rename = "overloaded_error")]
    OverloadedError,

    #[serde(rename = "permission_error")]
    PermissionError,

    #[serde(rename = "rate_limit_error")]
    RateLimitError,

    #[serde(rename = "timeout_error")]
    TimeoutError,
}

#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ErrorResponseType {
    Error,
}
