import { mergeRustFiles } from "../lib/merge-rust.js";
import { SCHEMAS_DIR, TYPES_RS_PATH, RUST_SCHEMA_FILES } from "./config.js";

mergeRustFiles(
  SCHEMAS_DIR,
  TYPES_RS_PATH,
  RUST_SCHEMA_FILES,
  "// Generated by quicktype from the Anthropic OpenAPI spec."
);
