// Generated by quicktype from the OpenAI OpenAPI spec.
// Do not edit manually — re-run `just generate-openai` instead.
//
// Placeholder: run `just sync-openai` and `just generate-openai` to populate.
